spring:
  application:
    name: tolimoli-pms
  
  # Database
  datasource:
    url: jdbc:postgresql://localhost:5432/pms_db
    username: pms_user
    password: pms_password
    driver-class-name: org.postgresql.Driver
  
  # JPA
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# Server
server:
  port: 8080

# Logging
logging:
  level:
    com.tolimoli.pms: INFO
    org.springframework: INFO