# Application configuration for PostgreSQL (default)
spring:
  application:
    name: tolimoli-pms
  
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/pms_db?useSSL=false&serverTimezone=UTC
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:pms_user}
    password: ${DB_PASSWORD:pms_password}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
    show-sql: true

# Server Configuration
server:
  port: 8080

# JWT Configuration
app:
  jwtSecret: mySecretKeyThatIsLongEnoughForHS512AlgorithmToWorkProperly1234567890
  jwtExpirationMs: 86400000

# Logging
logging:
  level:
    com.tolimoli.pms: INFO
    org.springframework: INFO
    org.hibernate.SQL: DEBUG

---
# Docker profile - PostgreSQL in Docker
spring:
  config:
    activate:
      on-profile: docker
  
  datasource:
    url: jdbc:postgresql://postgres:5432/pms_db
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:pms_user}
    password: ${DB_PASSWORD:pms_password}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

---
# Local profile - Local PostgreSQL
spring:
  config:
    activate:
      on-profile: local
  
  datasource:
    url: jdbc:postgresql://localhost:5432/pms_db
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:pms_user}
    password: ${DB_PASSWORD:pms_password}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect